"use client";

import { flexRender, functionalUpdate, getCoreRowModel, getFilteredRowModel, getSortedRowModel, useReactTable, type ColumnDef, type ColumnPinningState, type RowSelectionState, type SortingState, type Updater } from "@tanstack/react-table";
import { useMemo, useState, type ReactNode } from "react";

export type DataGridColumn<Row> = { id: string; header: ReactNode; accessorKey?: keyof Row & string; cell?: (row: Row) => ReactNode; sortable?: boolean; size?: number; minSize?: number; maxSize?: number; align?: "start" | "center" | "end" };
export type DataGridProps<Row extends { id: string }> = { rows: Row[]; columns: DataGridColumn<Row>[]; caption?: string; selectable?: boolean; selectedIds?: string[]; defaultSelectedIds?: string[]; onSelectedIdsChange?: (ids: string[]) => void; sorting?: SortingState; defaultSorting?: SortingState; onSortingChange?: (sorting: SortingState) => void; globalFilter?: string; pinnedColumns?: ColumnPinningState; empty?: ReactNode; className?: string };

export default function DataGrid<Row extends { id: string }>({ rows, columns, caption, selectable = false, selectedIds, defaultSelectedIds = [], onSelectedIdsChange, sorting, defaultSorting = [], onSortingChange, globalFilter, pinnedColumns, empty, className }: DataGridProps<Row>) {
  const [internalSorting, setInternalSorting] = useState<SortingState>(defaultSorting);
  const [internalSelection, setInternalSelection] = useState<RowSelectionState>(() => Object.fromEntries(defaultSelectedIds.map((id) => [id, true])));
  const resolvedSorting = sorting ?? internalSorting;
  const resolvedSelection = selectedIds ? Object.fromEntries(selectedIds.map((id) => [id, true])) : internalSelection;
  const resolvedPinning = pinnedColumns ?? { left: [], right: [] };
  const defs = useMemo<ColumnDef<Row>[]>(() => {
    const dataColumns = columns.map((column): ColumnDef<Row> => ({ id: column.id, header: () => column.header, accessorKey: column.accessorKey, cell: column.cell ? ({ row }) => column.cell!(row.original) : ({ getValue }) => getValue() as ReactNode, enableSorting: column.sortable, size: column.size, minSize: column.minSize, maxSize: column.maxSize, meta: { align: column.align } }));
    if (!selectable) return dataColumns;
    return [{ id: "__select__", size: 42, enableSorting: false, enableResizing: false, header: ({ table }) => <input type="checkbox" aria-label="Select all rows" checked={table.getIsAllRowsSelected()} ref={(node) => { if (node) node.indeterminate = table.getIsSomeRowsSelected(); }} onChange={table.getToggleAllRowsSelectedHandler()} />, cell: ({ row }) => <input type="checkbox" aria-label={`Select row ${row.id}`} checked={row.getIsSelected()} disabled={!row.getCanSelect()} onChange={row.getToggleSelectedHandler()} /> }, ...dataColumns];
  }, [columns, selectable]);
  const updateSorting = (updater: Updater<SortingState>) => { const next = functionalUpdate(updater, resolvedSorting); if (sorting === undefined) setInternalSorting(next); onSortingChange?.(next); };
  const updateSelection = (updater: Updater<RowSelectionState>) => { const next = functionalUpdate(updater, resolvedSelection); if (selectedIds === undefined) setInternalSelection(next); onSelectedIdsChange?.(Object.keys(next).filter((id) => next[id])); };
  const table = useReactTable({ data: rows, columns: defs, getRowId: (row) => row.id, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel(), getFilteredRowModel: getFilteredRowModel(), enableRowSelection: selectable, columnResizeMode: "onChange", state: { sorting: resolvedSorting, rowSelection: resolvedSelection, globalFilter, columnPinning: resolvedPinning }, onSortingChange: updateSorting, onRowSelectionChange: updateSelection });
  return <div className={className} data-vc-component="data-grid"><table style={{ width: table.getTotalSize() }}>{caption && <caption>{caption}</caption>}<thead>{table.getHeaderGroups().map((group) => <tr key={group.id}>{group.headers.map((header) => <th key={header.id} colSpan={header.colSpan} style={{ width: header.getSize() }} aria-sort={header.column.getIsSorted() === "asc" ? "ascending" : header.column.getIsSorted() === "desc" ? "descending" : undefined} data-vc-pinned={header.column.getIsPinned() || undefined} data-vc-align={(header.column.columnDef.meta as { align?: string } | undefined)?.align}><div>{header.isPlaceholder ? null : header.column.getCanSort() ? <button type="button" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}</button> : flexRender(header.column.columnDef.header, header.getContext())}</div>{header.column.getCanResize() && <div role="separator" aria-orientation="vertical" aria-label={`Resize ${header.id} column`} onDoubleClick={() => header.column.resetSize()} onMouseDown={header.getResizeHandler()} onTouchStart={header.getResizeHandler()} data-vc-column-resizer data-vc-resizing={header.column.getIsResizing() || undefined} />}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.length === 0 ? <tr><td colSpan={defs.length} data-vc-grid-empty>{empty}</td></tr> : table.getRowModel().rows.map((row) => <tr key={row.id} data-vc-selected={row.getIsSelected() || undefined}>{row.getVisibleCells().map((cell) => <td key={cell.id} style={{ width: cell.column.getSize() }} data-vc-pinned={cell.column.getIsPinned() || undefined} data-vc-align={(cell.column.columnDef.meta as { align?: string } | undefined)?.align}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div>;
}
